# -*- coding: utf-8 -*-
"""agents/report_agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FMJIIXc6a9Lv13NvIo47X5RU-uMr2UYS
"""

class ReportAgent:
    def generate_report(self, candidate_name, skill_analysis, market_summary):
        candidate_skills = set(skill_analysis["explicit_skills"] +
                               skill_analysis["implicit_skills"] +
                               skill_analysis["transferable_skills"])
        market_skills = [kw for kw, _ in market_summary["top_skills"]]

        strengths = [s for s in market_skills if s in candidate_skills]
        gaps = [s for s in market_skills if s not in candidate_skills]

        report = f"# Skill Gap Report for {candidate_name}\n\n"

        report += "## Key Strengths\n"
        report += "\n".join(f"- {s}" for s in strengths) or "- None\n"

        report += "\n\n## Skill Gaps (Priority Areas)\n"
        report += "\n".join(f"- {s}" for s in gaps) or "- None\n"

        report += "\n\n## Personalized Upskilling Plan\n"
        if gaps:
            report += "### Short-term (1–2 months)\n"
            for s in gaps[:2]:
                report += f"- Learn **{s}** via online course + mini project\n"

            report += "\n### Medium-term (3–6 months)\n"
            for s in gaps[2:4]:
                report += f"- Build portfolio project with **{s}**\n"

            report += "\n### Long-term (6+ months)\n"
            for s in gaps[4:]:
                report += f"- Gain real-world experience in **{s}**\n"
        else:
            report += "- Deepen existing expertise\n"

        return report