# -*- coding: utf-8 -*-
"""agents/parse_cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FMJIIXc6a9Lv13NvIo47X5RU-uMr2UYS
"""

{
  "name": "Risafya Tabrina Aurelia",
  "contact": {"email":"risafya01@gmail.com", "phone":"+6285942976204"},
  "summary": "Physics graduate with a focus on data analysis, machine learning, and proficient in embedded systems. Hands-on experience in data processing, visualization, and model building. Eager to apply technical expertise in a Data Analyst role.",
  "skills": ["python","tensorflow","sklearn","arduino"],
  "experience": [
    {"title":"Data Research/Software Test Intern","company":"BRIN","start":"2023","end":"2023","desc":"Focused on wave modelling data analysis and visualization with MATLAB and Python."},
    {"title":"Final Thesis","start":"2023","end":"2024","desc":"Worked on building emotion recognition system with Python and Random Forest."},
    {"title":"Freelance Coding Teacher","company":"ruangguru","start":"2025","desc":"Teach students basic coding fundamental (Python)"}
  ],
  "education":["B.Sc. in Physics, Islamic State University Jakarta, 2024"],
  "projects":[ {"name":"Emotion recognition","desc":"Arduino mic + RF + RandomForest"} ]
}

class CVParserAgent:
    def parse(self, cv_text: str):
        lines = cv_text.splitlines()
        sections = {"education": "", "experience": "", "skills": "", "projects": ""}
        current = None

        for line in lines:
            clean = line.strip()
            if not clean:
                continue
            lower = clean.lower()
            if "education" in lower:
                current = "education"
            elif "experience" in lower:
                current = "experience"
            elif "skills" in lower:
                current = "skills"
            elif "projects" in lower:
                current = "projects"
            elif current:
                sections[current] += clean + "\n"

        parsed = {
            "name": lines[0].strip(),  # assume first line is name
            "education": sections["education"].strip(),
            "experience": sections["experience"].strip(),
            "skills": [s.strip().lower() for s in sections["skills"].split(",") if s.strip()],
            "projects": sections["projects"].strip(),
        }
        return parsed