# -*- coding: utf-8 -*-
"""agents/skill_analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FMJIIXc6a9Lv13NvIo47X5RU-uMr2UYS
"""

class SkillAnalyzerAgent:
    IMPLIED_SKILLS = {
        "tensorflow": ["deep learning", "neural networks"],
        "random forest": ["ensemble methods", "supervised learning"],
        "matlab": ["numerical computing", "signal processing"],
        "arduino": ["embedded systems", "hardware integration"],
        "logistic regression": ["classification", "statistics"],
        "teach": ["communication", "mentoring", "leadership"],
    }

    def analyze(self, parsed_cv: dict):
        explicit = parsed_cv.get("skills", [])
        text = (parsed_cv.get("experience", "") + " " + parsed_cv.get("projects", "")).lower()

        implicit = set()
        transferable = set()

        for key, implied in self.IMPLIED_SKILLS.items():
            if key in text:
                implicit.update(implied)

        if "project" in text or "robot" in text:
            transferable.update(["problem solving", "project management"])

        return {
            "explicit_skills": explicit,
            "implicit_skills": sorted(list(implicit)),
            "transferable_skills": sorted(list(transferable)),
        }