# -*- coding: utf-8 -*-
"""orchestrator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FMJIIXc6a9Lv13NvIo47X5RU-uMr2UYS
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone -b agents https://github.com/risafya/ai-agent-assessment.git
# %cd ai-agent-assessment
!ls

from agents_parse_cv import CVParserAgent
from agents_skill_analyzer import SkillAnalyzerAgent
from agents_market_agent import MarketIntelligenceAgent
from agents_report_agent import ReportAgent


def run_pipeline(cv_file, role="Senior AI Engineer"):
    with open(cv_file) as f:
        text = f.read()

    parser = CVParserAgent()
    analyzer = SkillAnalyzerAgent()
    market_agent = MarketIntelligenceAgent()
    reporter = ReportAgent()

    parsed_cv = parser.parse(text)
    skill_analysis = analyzer.analyze(parsed_cv)
    market_summary = market_agent.analyze_market(role)
    report = reporter.generate_report(parsed_cv["name"], skill_analysis, market_summary)

    with open("sample_report.md", "w") as f:
        f.write(report)

    return report

if __name__ == "__main__":
    final = run_pipeline("sample_cv.txt", "Senior AI Engineer")
    print(final)